{{- if .Values.iamStaffPortalApi.enabled }}
{{- if .Values.iamStaffPortalApi.loginProviders }}
{{- $values := .Values.iamStaffPortalApi -}}
{{- $context := dict "Values" (merge (deepCopy $values) (dict "global" .Values.global)) "Chart" .Chart "Release" .Release "Files" .Files "Capabilities" .Capabilities -}}
{{- with $context -}}
{{- $keycloakBaseUrl := include "common.tplvalues.render" (dict "value" .Values.global.keycloakBaseUrl "context" $) -}}
{{- $oauthCallbackUrl := printf "https://%s/auth/callback" (include "common.tplvalues.render" (dict "value" .Values.hostname "context" $)) -}}
{{- $defaultRedirectUri := include "common.tplvalues.render" (dict "value" .Values.global.staffPortalDefaultRedirectUri "context" $) -}}
{{- $providers := list -}}
{{- range .Values.loginProviders }}
{{- $realmBase := printf "%s/realms/%s" $keycloakBaseUrl .realm -}}
{{- $provider := dict
  "id" .id
  "user_type" .userType
  "provider_name" .providerName
  "description" .description
  "icon_base64" "NULL"
  "client_id" .clientId
  "client_secret" .clientSecret
  "token_endpoint_auth_method" .tokenEndpointAuthMethod
  "keymanager_app_id" ""
  "keymanager_ref_id" ""
  "authorization_endpoint" (printf "%s/protocol/openid-connect/auth" $realmBase)
  "userinfo_endpoint" (printf "%s/protocol/openid-connect/userinfo" $realmBase)
  "token_endpoint" (printf "%s/protocol/openid-connect/token" $realmBase)
  "server_metadata_url" (printf "%s/.well-known/openid-configuration" $realmBase)
  "adapter_name" ""
  "jwks_uri" (printf "%s/protocol/openid-connect/certs" $realmBase)
  "jwt_assertion_aud" "NULL"
  "scope" .scope
  "enable_pkce" .enablePkce
  "extra_authorize_params" "NULL"
  "issuer" $realmBase
  "audiences" ""
  "oauth_callback_url" $oauthCallbackUrl
  "default_redirect_uri" $defaultRedirectUri
  "created_at" "2026-01-01 00:00:00"
  "updated_at" "2026-01-01 00:00:00"
  "active" .active
-}}
{{- $providers = append $providers $provider -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-login-providers
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  login_providers.json: {{ $providers | toJson | quote }}
{{- end -}}
{{- end }}
{{- end }}
